name = "finance-app"
pages_build_output_dir = "dist"
compatibility_date = "2024-05-03"

[[d1_databases]]
binding = "DB"
database_name = "patrimonio-db"
database_id = "60db20f5-1aa6-403c-90a6-69fc1e307913"
migrations_dir = "drizzle"
